export const RouterPath = {
  onboarding1: "/",
  communityPage: "/community",
  postPage: "/community/post",
  postDetailPage: "/community/post/detail",
  postWritePage: "/community/write",
  myPage: "/mypage",
  login: "/login",
  signup: "/signup",
  onboarding2: "/onboarding2",
  onboarding3: "/onboarding3",
  onboarding4: "/onboarding4",
  heartlist: "/heartlist",
  medicalReportResultPage: "/medical-report",
  analyzePage: "/analyze-processing-page",
  analyzeResultPage: "/analyze-result-page",
  analyzeDiagnosisPage: "/analyze-diagnosis",
  chatPage: "/lifestyle-chat",
  tempDiagnosisUploadPage: "/temp-upload",
  shopping: "/shopping",
  record: "/record",
};
